### ISSUE TITLE
to add new codes for file access modes in (advanced/file_handling.py)

### ISSUE THREAD

**Issue by izumigoto** [huangsam/ultimate-python#116]
Hey there! @huangsam 
python file handling expands not only to text files but binary and csv files too! and many more - a  important feature of python which can scrap data across different files. and that's why the the knowledge to know about all the file handling modes in python makes the learner more of a prominent coder.
 
Hence i would like to contribute to (advanced/file_handling.py) inserting r+(read and write),w+(write and read),a+(append and read),binary file modes rb,wb,rb,rb+,wb+ etc and the same for csv files with these modes
thanks

**Comment by huangsam** [comment]
@izumigoto you're welcome to contribute back to the code. I look forward to seeing your PR

**Comment by izumigoto** [comment]
@huangsam  heyo kinda new to open source contribution
could you please provide info on why am i getting a error on my PR.

**Comment by huangsam** [comment]
Consider reading the logs of the CircleCI build to get more insights. You can see that the particular build failed on `flake8` lint rules: https://app.circleci.com/pipelines/github/huangsam/ultimate-python/794/workflows/48a5b4f4-ae52-4a56-9ec2-4d6539c70ebd/jobs/800

**Comment by huangsam** [comment]
Closing #118 as I sense the thing that could have been done in that case is just adding more docstring content about the different modes. If you still find this issue to be interesting, please reopen this. Thanks again for contributing to Ultimate Python!
