### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by JoseDeFreitas** [huangsam/ultimate-python#36]
Hello 👋.
I saw there's a translation of this repository into Korean and Chinese. I'm a native Spanish speaker that has previously translated other projects into Spanish and would want to translate this into Spanish too.
I'm opening this issue because I want to know first if you're accepting translations. Please let me know. Thank you in advance.

**Comment by huangsam** [comment]
@JoseDeFreitas that's amazing! Thanks for expressing your interest in translating the `README` contents to Spanish. I'm accepting translations 👍

**Comment by huangsam** [comment]
Now that the translation has been merged, I will deem this issue as resolved. Thanks again @JoseDeFreitas! 👍
