### ISSUE TITLE
Can I use this code for online lecture?

### ISSUE THREAD

**Issue by godaji** [huangsam/ultimate-python#43]
Hello. Thanks for releasing a good open source.
I'm Korean and I'm trying to teach Python online in Korea.
Would it be ok to use the code here as an example?
It's for commercial purposes. It's under the MIT license, but I think it's better to ask.

**Comment by huangsam** [comment]
@godaji thanks for reaching out about the code. Feel free to use the code here for educational purposes, but please reference the repository / source links in your slides/ book / etc. while teaching. If you also have the course online somewhere, please share the link for it as I'd be curious to see how you leverage the source code 👍

Let me know if you still have any questions or concerns.

**Comment by godaji** [comment]
Thank you. I will do as you said.

**Comment by amauludin3** [comment]
Yes for sure my brader go for itOn 1 Sep 2021 08:56, godaji ***@***.***> wrote:
Thank you. I will do as you said.

**Comment by AK00711** [comment]
Please unsubscribe
