### ISSUE TITLE
Design Patterns in Python

### ISSUE THREAD

**Issue by ayushsingh12march** [huangsam/ultimate-python#47]
**Is your feature request related to a problem? Please describe.**
Design patterns like Factory methods are very common in any Programming languages and they will add value to this repo

**Describe the solution you'd like**
I can some of them with neat comments following the protocols of this repo

**Additional context**
Please assign it to me

**Comment by huangsam** [comment]
@ayushsingh12march thanks for your suggestion. You may notice that I have referenced [faif/python-patterns](https://github.com/faif/python-patterns) as a design pattern resource - it has many Python examples of the famous Gang of Four patterns, and more.

You may also have noticed that I incorporate design patterns into some of the lessons already:

- https://github.com/huangsam/ultimate-python/blob/master/ultimatepython/classes/iterator_class.py
- https://github.com/huangsam/ultimate-python/blob/master/ultimatepython/advanced/decorator.py
- https://github.com/huangsam/ultimate-python/blob/master/ultimatepython/advanced/mixin.py

Was there a particular design pattern or patterns that you wanted to showcase that is missing in this repository?

**Comment by huangsam** [comment]
I haven't seen any activity on this issue in the past 15 days so I'm going to close this issue. Feel free to raise another issue if you find something that can be enhanced in this repository.
