### ISSUE TITLE
"AssertionError" in running the file expression.py

### ISSUE THREAD

**Issue by jsmjsm** [huangsam/ultimate-python#6]

**Comment by jsmjsm** [comment]
When I try to run the `expression.py` in `syntax` directory, I got the "AssertionError".
I think there is something wrong with the expression:

```
    assert x / 2 == 0.5
```

Then, I change the int `2` to float `2.0`

**Comment by huangsam** [comment]
@jsmjsm thanks for raising this issue up. Which version of Python were you running with? I expect the original line to run successfully with Python 3.x but not Python 2.x.

My test suite is running with Python 3.8 FYI and everything is running smoothly.

**Comment by huangsam** [comment]
Here are some more resources to explain why I think the line you're reporting fails on Python 2.x:

- https://stackoverflow.com/questions/21316968/division-in-python-2-7-and-3-3
- https://stackoverflow.com/questions/2958684/python-division

**Comment by huangsam** [comment]
Added disclaimers with commit 53ec3a5f119e229b959e0964c2c14dade3b1eb6e - I'm closing this issue as I believe it has been resolved. All the best with your Python learning!
