### ISSUE TITLE
Adding French and Japanese README.md

### ISSUE THREAD

**Issue by JAGDF** [huangsam/ultimate-python#67]
**Is your feature request related to a problem? Please describe.**
I am trying to make a a French and Japanese README for the repository.

**Describe the solution you'd like**
When I'm finished translating, I'll send a pull request to you and see if you approve.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by huangsam** [comment]
That's excellent! Thanks for taking the initiative to make new README formats that are accessible to other Python newcomers and veterans alike.

**Comment by huangsam** [comment]
I would suggest sending two pull requests if you can do so. One PR for Japanese. One PR for French. I think this will help with simplifying the review process, as I typically try to get folks in my network to cross check one README translation at a time.

**Comment by JAGDF** [comment]
OK. When I'm finished the French .md file, I'll send a PR. The Japanese one I'll do after the French .md file.

**Comment by huangsam** [comment]
Hi @JAGDF. It's been a couple of months since I last heard from you. I'd like to keep this issue up, but I'd prefer to close it if I don't hear back from you by end of February. I hope we can collaborate more on this translation!

**Comment by huangsam** [comment]
Hey it's that time of February where I am about to close this ticket. That being said, you're welcome to reopen this ticket in the future when you find the time to pursue this again. Thanks again for creating this ticket. I look forward to collaborating again.
