### ISSUE TITLE
Deepfake

### ISSUE THREAD

**Issue by kidrockmusic** [huangsam/ultimate-python#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huangsam** [comment]
Hi @kidrockmusic thanks for submitting this issue. Unfortunately, it's not clear exactly what the issue is here. I'm closing this issue for now
