### ISSUE TITLE
Adding File Handling to the Python Learning List

### ISSUE THREAD

**Issue by ArcXeon** [huangsam/ultimate-python#76]
**Suggestion-**
File handling deserves a place on the list due to its fundamental role in Python programming. It encompasses the essential skills required to interact with files, which are ubiquitous in software development.

Here's why it's crucial to include file handling:

Data Storage: Files are commonly used to store data, such as user preferences, configuration settings, or even entire datasets. Learning file handling allows developers to read and write data effectively.

External Data Sources: In real-world applications, you often need to read data from external files, like text, CSV, JSON, or XML files. File handling equips you with the ability to extract and process this information.

Data Persistence: When building applications, it's crucial to save data so that it can be used later. File handling enables the persistence of data, ensuring that it remains available across sessions.

Logging: Many applications log events and errors to files. Understanding file handling is essential for managing log files effectively.

**Comment by ArcXeon** [comment]
I am interested in contributing to this resource compilation, so if you like this suggestion could you assign it to me?

**Comment by huangsam** [comment]
Hi @ArcXeon thanks for raising up your interest. How were you planning to teach file handling concept(s) to people?

Also, what did you think of these lessons?

- https://github.com/huangsam/ultimate-python/blob/master/ultimatepython/advanced/context_manager.py
- https://github.com/huangsam/ultimate-python/blob/master/ultimatepython/advanced/data_format.py

I'd like to know if there's more that can be done in those lessons to showcase file handling / file formats.

**Comment by ArcXeon** [comment]
Hi @huangsam, the context_manager.py  provides a good example of how to create and use context managers in Python, specifically for handling file-like objects using the StringIO class. But I think it  doesn't directly demonstrate all aspects of file handling basics (like reading, writing, or appending to files on disk).

An additional code can be created to demonstrate reading from, writing to, or appending to real files on disk using the built-in open function and various modes like "r" (read), "w" (write), and "a" (append). This would give new learners a more comprehensive understanding of file handling in Python. I think this code can be added in the syntax with beginner level difficulty.

**Comment by huangsam** [comment]
I think that file oriented stuff is complex. Not sure if it's what I would teach early on. Also we'd likely want to limit to in-memory file manipulation due to the nature of this repo

Do you think adding code or comments to the later lessons could help here?

**Comment by ArcXeon** [comment]
So maybe it can be added in advanced or maybe just adding it as an external resource along with the context manager or data format.

**Comment by huangsam** [comment]
Yea how does that sound?

**Comment by huangsam** [comment]
Hi @ArcXeon do you have any additional Qs or concerns? If not, feel free to create the PR in the next few weeks. Looking forward to more collaborations together!

**Comment by ArcXeon** [comment]
@huangsam So like I should proceed with my last suggestion and make a PR ?

**Comment by huangsam** [comment]
Yes you can make a PR
